version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dbpus
      MYSQL_USER: pram
      MYSQL_PASSWORD: pram
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./dbpus.sql:/docker-entrypoint-initdb.d/dbpus.sql
    ports:
      - 3306:3306
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/node_app
      - '/node_app/node_modules'
    restart: always
    depends_on:
      - mysqldb